export const PKD_CODES = [
  { code: '01.11.Z', name: 'Uprawa zbóż (z wyłączeniem ryżu), roślin strączkowych i nasion oleistych' },
  { code: '01.13.Z', name: 'Uprawa warzyw, uprava roślin bulwiastych i korzeniowych' },
  { code: '01.21.Z', name: 'Uprawa winorośli' },
  { code: '01.25.Z', name: 'Uprawa pozostałych drzew i krzewów owocowych oraz orzechów' },
  { code: '01.41.Z', name: 'Chów i hodowla bydła' },
  { code: '01.46.Z', name: 'Chów i hodowla świń' },
  { code: '01.47.Z', name: 'Chów i hodowla drobiu' },
  { code: '02.10.Z', name: 'Leśnictwo i pozostała gospodarka leśna' },
  { code: '03.11.Z', name: 'Rybołówstwo morskie' },
  { code: '03.21.Z', name: 'Akwakultura morska' },
  { code: '05.10.Z', name: 'Wydobywanie węgla kamiennego' },
  { code: '08.11.Z', name: 'Wydobywanie kamienia budowlanego i kamienia ozdobnego' },
  { code: '10.11.Z', name: 'Przetwarzanie i konserwowanie mięsa' },
  { code: '10.13.Z', name: 'Produkcja wyrobów z mięsa, włączając wyroby z mięsa drobiowego' },
  { code: '10.20.Z', name: 'Przetwarzanie i konserwowanie ryb, skorupiaków i mięczaków' },
  { code: '10.31.Z', name: 'Przetwarzanie i konserwowanie ziemniaków' },
  { code: '10.39.Z', name: 'Pozostałe przetwarzanie i konserwowanie owoców i warzyw' },
  { code: '10.41.Z', name: 'Produkcja olejów i tłuszczów' },
  { code: '10.51.Z', name: 'Przetwórstwo mleka i produkcja serów' },
  { code: '10.61.Z', name: 'Produkcja wyrobów młynarskich' },
  { code: '10.71.Z', name: 'Produkcja pieczywa; produkcja świeżych wyrobów cukierniczych' },
  { code: '10.73.Z', name: 'Produkcja makaronów, kuskusu i podobnych mącznych produktów spożywczych' },
  { code: '10.81.Z', name: 'Produkcja cukru' },
  { code: '10.82.Z', name: 'Produkcja wyrobów kakaowych i czekolady oraz wyrobów cukierniczych' },
  { code: '10.84.Z', name: 'Produkcja przypraw i produktów aromatyzujących' },
  { code: '10.85.Z', name: 'Produkcja gotowych posiłków i potraw' },
  { code: '10.89.Z', name: 'Produkcja pozostałych artykułów spożywczych, gdzie indziej niesklasyfikowana' },
  { code: '11.01.Z', name: 'Destylacja, rektyfikacja i mieszanie alkoholi' },
  { code: '11.02.Z', name: 'Produkcja wina z winogron' },
  { code: '11.05.Z', name: 'Produkcja piwa' },
  { code: '11.07.Z', name: 'Produkcja napojów bezalkoholowych; produkcja wód mineralnych i pozostałych wód butelkowanych' },
  { code: '13.10.Z', name: 'Przygotowanie i przędzenie włókien tekstylnych' },
  { code: '13.20.Z', name: 'Tkactwo' },
  { code: '13.30.Z', name: 'Wykańczanie wyrobów tekstylnych' },
  { code: '14.11.Z', name: 'Produkcja odzieży skórzanej' },
  { code: '14.12.Z', name: 'Produkcja odzieży roboczej' },
  { code: '14.13.Z', name: 'Produkcja pozostałej odzieży wierzchniej' },
  { code: '14.14.Z', name: 'Produkcja bielizny' },
  { code: '14.19.Z', name: 'Produkcja pozostałej odzieży i dodatków do odzieży' },
  { code: '15.11.Z', name: 'Wyprawianie i wykańczanie skór; produkcja walizek, torebek, rymarskich i szewskich wyrobów skórzanych' },
  { code: '15.20.Z', name: 'Produkcja obuwia' },
  { code: '16.10.Z', name: 'Tartacznictwo oraz impregnacja drewna' },
  { code: '16.21.Z', name: 'Produkcja forniru i płyt drewnopochodnych' },
  { code: '16.22.Z', name: 'Produkcja parkietów składanych' },
  { code: '16.23.Z', name: 'Produkcja pozostałych wyrobów stolarskich i ciesielskich dla budownictwa' },
  { code: '16.24.Z', name: 'Produkcja opakowań z drewna' },
  { code: '16.29.Z', name: 'Produkcja pozostałych wyrobów z drewna; produkcja wyrobów z korka, słomy i materiałów używanych do wyplatania' },
  { code: '17.11.Z', name: 'Produkcja masy celulozowej' },
  { code: '17.12.Z', name: 'Produkcja papieru i tektury' },
  { code: '17.21.Z', name: 'Produkcja papieru falistego oraz tektury falistej i opakowań z papieru i tektury' },
  { code: '17.22.Z', name: 'Produkcja wyrobów higienicznych i toaletowych z papieru' },
  { code: '17.23.Z', name: 'Produkcja wyrobów papierniczych' },
  { code: '17.24.Z', name: 'Produkcja tapet' },
  { code: '17.29.Z', name: 'Produkcja pozostałych wyrobów z papieru i tektury' },
  { code: '18.11.Z', name: 'Drukowanie gazet' },
  { code: '18.12.Z', name: 'Pozostała działalność drukarska' },
  { code: '18.13.Z', name: 'Przygotowanie do druku i publikowania' },
  { code: '18.14.Z', name: 'Introligatorstwo i podobne usługi' },
  { code: '18.20.Z', name: 'Reprodukcja zapisanych nośników informacji' },
  { code: '19.10.Z', name: 'Produkcja produktów koksowniczych' },
  { code: '19.20.Z', name: 'Produkcja produktów rafinacji ropy naftowej' },
  { code: '20.11.Z', name: 'Produkcja gazów przemysłowych' },
  { code: '20.12.Z', name: 'Produkcja barwników i pigmentów' },
  { code: '20.13.Z', name: 'Produkcja pozostałych podstawowych chemikaliów nieorganicznych' },
  { code: '20.14.Z', name: 'Produkcja pozostałych podstawowych chemikaliów organicznych' },
  { code: '20.15.Z', name: 'Produkcja nawozów i związków azotowych' },
  { code: '20.16.Z', name: 'Produkcja tworzyw sztucznych w formach podstawowych' },
  { code: '20.17.Z', name: 'Produkcja kauczuku syntetycznego w formach podstawowych' },
  { code: '20.20.Z', name: 'Produkcja pestycydów i pozostałych środków agrochemicznych' },
  { code: '20.30.Z', name: 'Produkcja farb, lakierów, podobnych powłok, farb drukarskich i kitu' },
  { code: '20.41.Z', name: 'Produkcja mydeł i detergentów, środków czyszczących i polerskich' },
  { code: '20.42.Z', name: 'Produkcja perfum i kosmetyków' },
  { code: '20.51.Z', name: 'Produkcja wyrobów pirotechnicznych' },
  { code: '20.52.Z', name: 'Produkcja klejów' },
  { code: '20.53.Z', name: 'Produkcja olejków eterycznych' },
  { code: '20.59.Z', name: 'Produkcja pozostałych wyrobów chemicznych, gdzie indziej niesklasyfikowana' },
  { code: '20.60.Z', name: 'Produkcja włókien sztucznych' },
  { code: '21.10.Z', name: 'Produkcja podstawowych substancji farmaceutycznych' },
  { code: '21.20.Z', name: 'Produkcja leków i pozostałych wyrobów farmaceutycznych' },
  { code: '22.11.Z', name: 'Produkcja opon i dętek; bieżnikowanie i regeneracja opon' },
  { code: '22.19.Z', name: 'Produkcja pozostałych wyrobów z gumy' },
  { code: '22.21.Z', name: 'Produkcja płyt, arkuszy, rur i kształtowników z tworzyw sztucznych' },
  { code: '22.22.Z', name: 'Produkcja opakowań z tworzyw sztucznych' },
  { code: '22.23.Z', name: 'Produkcja wyrobów budowlanych z tworzyw sztucznych' },
  { code: '22.29.Z', name: 'Produkcja pozostałych wyrobów z tworzyw sztucznych' },
  { code: '23.11.Z', name: 'Produkcja szkła płaskiego' },
  { code: '23.12.Z', name: 'Formowanie i przetwarzanie szkła płaskiego' },
  { code: '23.13.Z', name: 'Produkcja wyrobów szklanych dla gospodarstw domowych i do celów dekoracyjnych' },
  { code: '23.14.Z', name: 'Produkcja włókien szklanych' },
  { code: '23.19.Z', name: 'Produkcja i przetwarzanie pozostałych wyrobów szklanych, włączając szkło techniczne' },
  { code: '23.20.Z', name: 'Produkcja wyrobów ogniotrwałych' },
  { code: '23.31.Z', name: 'Produkcja płytek i płyt ceramicznych' },
  { code: '23.32.Z', name: 'Produkcja cegieł, dachówek i pozostałych ceramicznych materiałów budowlanych' },
  { code: '23.41.Z', name: 'Produkcja ceramicznych wyrobów gospodarstwa domowego i wyrobów dekoracyjnych' },
  { code: '23.42.Z', name: 'Produkcja ceramicznych wyrobów sanitarnych' },
  { code: '23.43.Z', name: 'Produkcja ceramicznych izolatorów i wyrobów izolacyjnych z ceramiki' },
  { code: '23.44.Z', name: 'Produkcja pozostałych wyrobów ceramicznych do zastosowań technicznych' },
  { code: '23.49.Z', name: 'Produkcja pozostałych wyrobów ceramicznych' },
  { code: '23.51.Z', name: 'Produkcja cementu' },
  { code: '23.52.Z', name: 'Produkcja wapna i gipsu' },
  { code: '23.61.Z', name: 'Produkcja wyrobów z betonu dla budownictwa' },
  { code: '23.62.Z', name: 'Produkcja wyrobów z gipsu dla budownictwa' },
  { code: '23.63.Z', name: 'Produkcja betonu towarowego' },
  { code: '23.64.Z', name: 'Produkcja zapraw' },
  { code: '23.65.Z', name: 'Produkcja wyrobów z włóknocementu' },
  { code: '23.69.Z', name: 'Produkcja pozostałych wyrobów z betonu, gipsu i cementu' },
  { code: '23.70.Z', name: 'Cięcie, formowanie i wykańczanie kamienia' },
  { code: '23.91.Z', name: 'Produkcja wyrobów ściernych' },
  { code: '23.99.Z', name: 'Produkcja pozostałych wyrobów z mineralnych surowców niemetalicznych, gdzie indziej niesklasyfikowana' }
];
